<?php
$db_file = __DIR__ . '/config/db.php';
$schema_file = __DIR__ . '/config/schema.sql';

$already_installed = false;
if (file_exists($db_file)) {
    // Check if it's already configured and working
    try {
        include $db_file;
        if (isset($pdo)) {
            $already_installed = true;
        }
    } catch (Exception $e) {
        // Not configured properly
    }
}

$message = "";
$message_type = "";

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$already_installed) {
    $db_host = $_POST['db_host'] ?? '127.0.0.1';
    $db_port = $_POST['db_port'] ?? '3306';
    $db_name = $_POST['db_name'] ?? 'rjpes_db';
    $db_user = $_POST['db_user'] ?? 'root';
    $db_pass = $_POST['db_pass'] ?? '';
    
    try {
        // 1. Try to connect to MySQL server (without database first)
        $dsn_no_db = "mysql:host={$db_host};port={$db_port};charset=utf8mb4";
        $options = [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        ];
        $temp_pdo = new PDO($dsn_no_db, $db_user, $db_pass, $options);
        
        // 2. Create database
        $temp_pdo->exec("CREATE DATABASE IF NOT EXISTS `{$db_name}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        
        // 3. Re-connect with database selected
        $dsn_with_db = "mysql:host={$db_host};port={$db_port};dbname={$db_name};charset=utf8mb4";
        $pdo = new PDO($dsn_with_db, $db_user, $db_pass, $options);
        
        // 4. Read and execute schema SQL
        if (file_exists($schema_file)) {
            $schema_sql = file_get_contents($schema_file);
            
            // Remove comments and split by semicolon
            $queries = explode(';', $schema_sql);
            
            $pdo->exec("USE `{$db_name}`");
            foreach ($queries as $query) {
                $query = trim($query);
                if (!empty($query)) {
                    $pdo->exec($query);
                }
            }
            
            // 5. Write config/db.php dynamically
            $db_config_code = "<?php\n"
                            . "// Database configuration (Generated by installer)\n"
                            . "define('DB_HOST', '{$db_host}');\n"
                            . "define('DB_PORT', '{$db_port}');\n"
                            . "define('DB_NAME', '{$db_name}');\n"
                            . "define('DB_USER', '{$db_user}');\n"
                            . "define('DB_PASS', '{$db_pass}');\n\n"
                            . "try {\n"
                            . "    \$dsn = \"mysql:host=\" . DB_HOST . \";port=\" . DB_PORT . \";dbname=\" . DB_NAME . \";charset=utf8mb4\";\n"
                            . "    \$options = [\n"
                            . "        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,\n"
                            . "        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,\n"
                            . "        PDO::ATTR_EMULATE_PREPARES   => false,\n"
                            . "    ];\n"
                            . "    \$pdo = new PDO(\$dsn, DB_USER, DB_PASS, \$options);\n"
                            . "} catch (PDOException \$e) {\n"
                            . "    die(\"Database connection failed. Please ensure MySQL is running and the database is imported. Error: \" . \$e->getMessage());\n"
                            . "}\n"
                            . "?>\n";
                            
            file_put_contents($db_file, $db_config_code);
            
            $message = "Database configured and RJPES tables initialized successfully!";
            $message_type = "success";
            $already_installed = true;
        } else {
            $message = "Schema SQL file config/schema.sql was not found.";
            $message_type = "danger";
        }
        
    } catch (PDOException $e) {
        $message = "Installation failed: " . $e->getMessage();
        $message_type = "danger";
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Database Setup - RJPES Portal</title>
    <link rel="stylesheet" href="assets/css/styles.css">
</head>
<body style="background-color: var(--primary-dark); display: flex; align-items: center; justify-content: center; min-height: 100vh;">

<main class="container" style="max-width: 550px;">
    <div class="card" style="box-shadow: var(--shadow-lg); padding: 2.5rem;">
        <div style="text-align: center; margin-bottom: 2rem;">
            <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="#d4af37" stroke-width="2" style="margin-bottom: 10px;">
                <ellipse cx="12" cy="5" rx="9" ry="3"/>
                <path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/>
                <path d="M3 12c0 1.66 4 3 9 3s9-1.34 9-3"/>
            </svg>
            <h2 style="font-family: var(--font-heading); color: var(--primary-color);">RJPES Database Installer</h2>
            <p style="font-size: 0.85rem; color: var(--text-muted); margin-top: 5px;">Set up your MySQL database and configurations</p>
        </div>

        <?php if (!empty($message)): ?>
            <div class="alert alert-<?php echo $message_type; ?>">
                <div><?php echo $message; ?></div>
            </div>
        <?php endif; ?>

        <?php if ($already_installed): ?>
            <div style="text-align: center; padding: 1.5rem 0;">
                <div style="color: var(--success-color); font-size: 3rem; margin-bottom: 1rem;">✓</div>
                <h3 style="color: var(--primary-color); margin-bottom: 10px;">System Ready</h3>
                <p style="color: var(--text-muted); font-size: 0.9rem; margin-bottom: 2rem;">RJPES Portal is installed. You can log in using the seed administrator account.</p>
                <a href="login.php" class="btn btn-dark" style="width: 100%; padding: 12px;">Go to Login Portal</a>
            </div>
        <?php else: ?>
            <form action="install.php" method="POST">
                <div class="form-group">
                    <label for="db_host">MySQL Database Host</label>
                    <input type="text" name="db_host" id="db_host" class="form-control" value="127.0.0.1" required>
                    <small style="color: var(--text-muted); font-size: 0.75rem;">Usually 127.0.0.1 or localhost</small>
                </div>

                <div class="form-group">
                    <label for="db_port">MySQL Port</label>
                    <input type="text" name="db_port" id="db_port" class="form-control" value="3306" required>
                </div>

                <div class="form-group">
                    <label for="db_name">Database Name</label>
                    <input type="text" name="db_name" id="db_name" class="form-control" value="rjpes_db" required>
                    <small style="color: var(--text-muted); font-size: 0.75rem;">Will be created automatically if it does not exist.</small>
                </div>

                <div class="form-group">
                    <label for="db_user">MySQL Username</label>
                    <input type="text" name="db_user" id="db_user" class="form-control" value="root" required>
                </div>

                <div class="form-group">
                    <label for="db_pass">MySQL Password</label>
                    <input type="password" name="db_pass" id="db_pass" class="form-control" placeholder="Leave empty if none">
                </div>

                <button type="submit" class="btn btn-primary" style="width: 100%; padding: 14px; margin-top: 1.5rem; font-weight: 700;">Initialize Database Setup</button>
            </form>
        <?php endif; ?>
    </div>
</main>

</body>
</html>
